### ISSUE TITLE
Running pre-commit just hangs

### ISSUE THREAD

**Issue by tskolnik** [igorshubovych/markdownlint-cli#106]
Hi there,

When running the pre-commit command, the process is stuck on installing the environment for this commit hook. I can run `markdownlint .` and that works fine; however invoking the command using the hook causes the process to just hang:

```
[INFO] Installing environment for git://github.com/igorshubovych/markdownlint-cli.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
```

My .pre-commit-config.yaml
```
  -   repo: git://github.com/igorshubovych/markdownlint-cli
      rev: v0.23.1
      hooks:
        -   id: markdownlint
```

My .markdownlintrc:
```
{
  "default": true,
  "line_length": false
}
```

My .markdownlint.yaml:
```
---
default: true
MD033: false # inline HTML - terraform-docs produces these
MD045: false # allow image with no tag
```

Any help on this would be helpful, thanks!

**Comment by DavidAnson** [comment]
You don’t need both `.markdownlintrc` and `.markdownlint.yaml`, but I don’t know why it’s getting stuck. You probably want to look into whatever tool you are using to set up the hook. For my part, I would expect it to need a reference to the npm package rather than the Git repository. The files in a Git repository are not necessarily executable as-is - it may be looking for something that does not exist.

**Comment by dnmvisser** [comment]
Hi, I wonder what the `.pre-commit-config.yaml` _should_ look like for use with this linter...?

**Comment by DavidAnson** [comment]
@dnmvisser @tskolnik Here is a sample `.pre-commit-config.yaml` that is known to work (in this case via the https://github.com/marketplace/actions/pre-commit GitHub Action):

```yaml
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.2.0
  hooks:
  - id: check-json
  - id: check-yaml
- repo: https://github.com/igorshubovych/markdownlint-cli
  rev: v0.24.0
  hooks:
  - id: markdownlint
```

If the `pre-commit` tool is still hanging for you, that is probably something outside the scope of `markdownlint-cli`.
