### ISSUE TITLE
Feature request: make this an integrated plugin for pre-commit

### ISSUE THREAD

**Issue by ira-bv** [igorshubovych/markdownlint-cli#129]
If nobody beats me to it, I'll try to donate instructions to config this manually as a generic plugin, and maybe the code to get to autoinstall as time permits.

**Comment by nschonni** [comment]
There is already https://github.com/igorshubovych/markdownlint-cli/blob/master/.pre-commit-hooks.yaml, is that not what is required?

**Comment by DavidAnson** [comment]
The basics work - I have a test that exercises this via pre-commit every day. What else did you have in mind?

**Comment by ira-bv** [comment]
ok, I tried adding this to my .pre-commit-config.yaml and it seems to work:

```
  - repo: https://github.com/igorshubovych/markdownlint-cli.git
    rev: ''
    hooks:
      - id: markdownlint
```

So I just suggest this appears in the README
