### ISSUE TITLE
Adding markdownlint-fix to precommit config?

### ISSUE THREAD

**Issue by rrauenza** [igorshubovych/markdownlint-cli#233]
Do you think it would be worth adding another hook for --fix?

I can do a pull request, but it's also a simple change I think.  Just checking in first on your thoughts...

**Comment by DavidAnson** [comment]
If pre-commit supports parameters, I would suggest that, I think. Else, another hook seems reasonable.

**Comment by janosh** [comment]
See https://pre-commit.com/#config-args.

Simple as

```yaml
- repo: local
  hooks:
    - id: some-hook
      args: [--first-arg, --second-arg]
```

**Comment by rrauenza** [comment]
I'd rather not use "local" so I can pin the repo via precommit and keep it in sync with the check mode...

**Comment by janosh** [comment]
@rrauenza I think you misunderstood. My example was just to demonstrate how to pass command line arguments to a hook. Put whatever you like for the repo.

**Comment by DavidAnson** [comment]
Are there concerns with https://github.com/igorshubovych/markdownlint-cli/pull/235 ? My limited understanding of pre-commit suggested it was a reasonable change.

**Comment by janosh** [comment]
@DavidAnson I don't see the need for #235. People who want to run with the `--fix` flag can can already do so like this:

```yml
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.29.0
    hooks:
      - id: markdownlint
        args: [--fix]
```

**Comment by DavidAnson** [comment]
And now they could do that by passing name "markdownlint-fix" and no args, right? I agree this is not necessary and I am normally against duplication, but I think it makes the idea of fixing during precommit more discoverable. I'm not expecting a lot of maintenance cost, so I'm inclined to leave it.

**Comment by DavidAnson** [comment]
Fixed by https://github.com/igorshubovych/markdownlint-cli/commit/2d2ba4746cdef3db7710ca6787a718a31469cc06

**Comment by rrauenza** [comment]
> @DavidAnson I don't see the need for #235. People who want to run with the `--fix` flag can can already do so like this:
> 
> ```yaml
>   - repo: https://github.com/igorshubovych/markdownlint-cli
>     rev: v0.29.0
>     hooks:
>       - id: markdownlint
>         args: [--fix]
> ```

This doesn't work if you want to have both in the precommit file -- a fix and a check...  the id's would duplicate.

I was assuming not every lint error could be fixed.   

Maybe having two is redundant... I didn't look to see how --fix works when / if there are errors it can't fix.

Is this actually redundant in my precommit config?

```
  - repo: https://github.com/rrauenza/markdownlint-cli
    rev: 68b557874fcdd9aa19d0872180268c3b1b38053c
    hooks:
       - id: markdownlint-fix
       - id: markdownlint

```
