### ISSUE TITLE
Pre-commit: all files are passed in pre-commit.ci

### ISSUE THREAD

**Issue by Guts** [igorshubovych/markdownlint-cli#239]
Hello,

First of all, thanks you for this CLI :).

I'm trying to use it as a pre-commit hook running on CI to autofix common errors from an heterogeneous pool of contributors to a static website. Here come:

- the [WIP pre-commit configuration](https://github.com/geotribu/website/blob/ci/markdownlint-precommit-2021-11/.pre-commit-config.yaml#L19-L34)
- [one of the pre-commit.ci result](https://results.pre-commit.ci/run/github/248722492/1637235418.kFg_IObnRvW6k9syW9YbHQ): you can see that ALL files are linted!

Am I missing something in the configuration?

----

**Secondary question**

What's the difference between:

```yaml
repos:
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.29.0
    hooks:
      - id: markdownlint
        args:
          [
            "--config",
            ".markdownlint.json",
            "--ignore-path",
            ".markdownlintignore",
            "--fix"
          ]
        language: node
        # language_version: "14.17.6"
        pass_filenames: true
        types: [file, markdown, non-executable]
```

and, after #235, removing `--fix` from args :

```yaml
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: bf8b1484934b89c791b9aab83c2c6cc950546be4
    hooks:
      - id: markdownlint-fix
        args:
          [
            "--config",
            ".markdownlint.json",
            "--ignore-path",
            ".markdownlintignore"
          ]
        language: node
        # language_version: "14.17.6"
        pass_filenames: true
        types: [file, markdown, non-executable]
```
