### ISSUE TITLE
json parser tries to parse nested toml

### ISSUE THREAD

**Issue by dennis-wey** [igorshubovych/markdownlint-cli#469]
I think this is a bug from https://github.com/igorshubovych/markdownlint-cli/issues/113

I'm having trouble getting the new config options to work with pre-commit:

`pre-commit-config.yaml`
```
repos:
  - repo: "https://github.com/igorshubovych/markdownlint-cli"
    rev: "v0.40.0"
    hooks:
      - id: "markdownlint-fix"
        args: [--config, pyproject.toml, --configPointer, "/tool/markdownlint"]
        verbose: true
```
`pyproject.toml`
```
[project]
name = "my-package"
description = "description"

[tool.markdownlint]
default = true
MD007.indent = 4
```

I get the following error:

```
pre-commit run -a
markdownlint-fix.........................................................Failed
- hook id: markdownlint-fix
- duration: 0.13s
- exit code: 1

Cannot read or parse config file 'pyproject.toml': Unable to parse 'pyproject.toml'; Parser 0: Unable to parse JSON(C) content, InvalidSymbol (offset 1, length 7), InvalidSymbol (offset 10, length 4), InvalidSymbol (offset 15, length 1), EndOfFileExpected (offset 17, length 12); Parser 1: Expected "=", [ \t] or [A-Za-z0-9_\-] but "." found.; Parser 2: end of the stream or a document separator is expected (2:1)

 1 | [project]
 2 | name = "my-package"
-----^
 3 | description = "description"
 4 | 
```
> 
> Process finished with exit code 1

Seems like it tries to apply the JSON Parser first to the toml file.
After that the right configuration is found with the toml parser and the actual formatting is taking place but the prior error is causing the action to exit with status code 1. 

This is especially problematic in ci workflows which rely on actions exit with status code 0 to pass
