### ISSUE TITLE
Pre-commit config does not honor rev

### ISSUE THREAD

**Issue by scotchneat** [igorshubovych/markdownlint-cli#538]
We noticed our CI jobs started failing linting all of the sudden (with no recent commits to relevant files).

```
 markdownlint-fix-docker..................................................Failed
- hook id: markdownlint-fix-docker
- exit code: 1
- files were modified by this hook

Unable to find image 'ghcr.io/igorshubovych/markdownlint-cli:latest' locally
latest: Pulling from igorshubovych/markdownlint-cli
```

While we have the following configured, which pins the `rev` to a specific repo tag:

```
  - repo: https://github.com/igorshubovych/markdownlint-cli/
    rev: v0.38.0
    hooks:
      - id: markdownlint-fix-docker
        stages: [pre-commit]
        args: ["--disable=MD013", "--"]
        exclude: docs/schema.md
```

The references to the docker image in the `.pre-commit-hooks.yaml` aren't defined with a tag ([here](https://github.com/igorshubovych/markdownlint-cli/blob/master/.pre-commit-hooks.yaml#L18) and [here](https://github.com/igorshubovych/markdownlint-cli/blob/master/.pre-commit-hooks.yaml#L25)). This results in the latest being pulled in CI (or any new install). 

Ideally, these images would be tagged to match the respective release.
